#pragma once

/**
 * @file IthacaConfig.h
 * @brief Configuration for IthacaPlayer JUCE plugin integration
 *
 * This config extends ithaca-core with JUCE-specific settings for the plugin.
 * It provides configuration for:
 * - Plugin identification (passed via CMake preprocessor defines)
 * - JUCE integration parameters
 * - GUI settings
 * - All core audio engine settings (inherited from base config)
 */

// ============================================================================
// VERSION
// ============================================================================

#define ITHACA_CORE_VERSION_MAJOR 1
#define ITHACA_CORE_VERSION_MINOR 1
#define ITHACA_CORE_VERSION_PATCH 0
#define ITHACA_CORE_VERSION_STRING "1.1.0"

// ============================================================================
// AUDIO ENGINE - Core Parameters
// ============================================================================
// Inherited from ithaca-core, but defined here for JUCE plugin use

// Voice management
#define ITHACA_MAX_VOICES 128
#define ITHACA_MAX_VELOCITY_LAYERS 8
#define ITHACA_DEFAULT_VOICE_GAIN 1.0f

// Sample rates (Hz)
#define ITHACA_DEFAULT_SAMPLE_RATE 44100
#define ITHACA_MIN_SAMPLE_RATE 22050
#define ITHACA_MAX_SAMPLE_RATE 192000

// Buffer sizes (samples)
#define ITHACA_DEFAULT_BLOCK_SIZE 512
#define ITHACA_MIN_BLOCK_SIZE 32
#define ITHACA_MAX_BLOCK_SIZE 2048  // Lower max for plugin (tighter latency requirements)

// MIDI parameters
#define ITHACA_MIDI_NOTE_MIN 0
#define ITHACA_MIDI_NOTE_MAX 127
#define ITHACA_MIDI_VELOCITY_MIN 0
#define ITHACA_MIDI_VELOCITY_MAX 127
#define ITHACA_DEFAULT_VELOCITY 80

// ============================================================================
// ENVELOPE - ADSR Configuration
// ============================================================================

#define ITHACA_ENVELOPE_TRIGGERS_END_ATTACK  0.99f
#define ITHACA_ENVELOPE_TRIGGERS_END_RELEASE 0.01f

#define ITHACA_DEFAULT_ATTACK_MS 10.0f
#define ITHACA_DEFAULT_DECAY_MS 200.0f
#define ITHACA_DEFAULT_SUSTAIN_LEVEL 0.7f
#define ITHACA_DEFAULT_RELEASE_MS 500.0f

// ============================================================================
// SAMPLE BANK PATHS
// ============================================================================
// NOTE: Sample bank paths are configured via samplebank-config-{PLUGIN_CODE}.json
// in the user's roaming profile directory, generated by CMake during build:
//
// - Windows: %APPDATA%\LordAudio\IthacaPlayer-{INSTRUMENT}\samplebank-config-{CODE}.json
// - macOS: ~/Library/Application Support/LordAudio/IthacaPlayer-{INSTRUMENT}/samplebank-config-{CODE}.json
// - Linux: ~/.local/share/LordAudio/IthacaPlayer-{INSTRUMENT}/samplebank-config-{CODE}.json
//
// The default path is configured in CMakeLists.txt via SAMPLE_BANK_PATH variable.

// ============================================================================
// PLUGIN IDENTIFICATION
// ============================================================================
// These are passed via CMake preprocessor defines:
// - ITHACA_PLUGIN_TARGET_NAME: e.g., "IthacaPlayer-VintageV"
// - ITHACA_PLUGIN_CODE: e.g., "VntV"
//
// They are used in SampleBankPathManager for config file naming.

// ============================================================================
// JUCE INTEGRATION
// ============================================================================

#define ITHACA_JUCE_INTEGRATION 1

// GUI Configuration
#define ITHACA_GUI_DEFAULT_WIDTH 800
#define ITHACA_GUI_DEFAULT_HEIGHT 600
#define ITHACA_GUI_MIN_WIDTH 600
#define ITHACA_GUI_MIN_HEIGHT 400

// GUI update rates (milliseconds)
#define ITHACA_GUI_STATS_UPDATE_MS 33        // ~30 FPS for performance stats
#define ITHACA_GUI_VOICE_ACTIVITY_UPDATE_MS 50  // 20 FPS for voice activity display

// Color scheme (ARGB hex format)
#define ITHACA_GUI_BG_COLOR_TOP 0xff2a2a2a
#define ITHACA_GUI_BG_COLOR_BOTTOM 0xff1a1a1a
#define ITHACA_GUI_TEXT_COLOR 0xffffffff
#define ITHACA_GUI_ACCENT_COLOR 0xff0088ff

// ============================================================================
// LOGGING - Plugin Mode
// ============================================================================

#define ITHACA_LOG_LEVEL_DEBUG 0
#define ITHACA_LOG_LEVEL_INFO 1
#define ITHACA_LOG_LEVEL_WARN 2
#define ITHACA_LOG_LEVEL_ERROR 3

// In plugin mode, reduce logging in release builds for performance
#ifdef NDEBUG
    #define ITHACA_DEFAULT_LOG_LEVEL ITHACA_LOG_LEVEL_WARN
    #define ITHACA_ENABLE_RT_LOGGING 0
#else
    #define ITHACA_DEFAULT_LOG_LEVEL ITHACA_LOG_LEVEL_DEBUG
    #define ITHACA_ENABLE_RT_LOGGING 1
#endif

#define ITHACA_LOG_DIR "core_logger"
#define ITHACA_LOG_FILENAME "core_logger.log"

// ============================================================================
// PERFORMANCE - Memory & Threading
// ============================================================================

#define ITHACA_USE_SHARED_ENVELOPE_DATA 1
#define ITHACA_OPTIMIZE_FOR_LOW_LATENCY 1
#define ITHACA_ENABLE_RT_SAFETY_CHECKS 1
#define ITHACA_VOICE_POOL_PREALLOCATE 1
#define ITHACA_ENABLE_DENORMAL_PROTECTION 1

// ============================================================================
// DEBUG - Development & Testing
// ============================================================================

#ifdef _DEBUG
    #define ITHACA_DEBUG_MODE 1
    #define ITHACA_ENABLE_ASSERTIONS 1
#else
    #define ITHACA_DEBUG_MODE 0
    #define ITHACA_ENABLE_ASSERTIONS 0
#endif

#if ITHACA_ENABLE_ASSERTIONS
    #include <cassert>
    #define ITHACA_ASSERT(condition) assert(condition)
    #define ITHACA_ASSERT_MSG(condition, message) assert((condition) && (message))
#else
    #define ITHACA_ASSERT(condition) ((void)0)
    #define ITHACA_ASSERT_MSG(condition, message) ((void)0)
#endif

// ============================================================================
// BACKWARD COMPATIBILITY - Legacy Macro Names
// ============================================================================
// These exist for backward compatibility with existing ithaca-core code.
// New code should use ITHACA_* prefixed names.

#define DEFAULT_SAMPLE_RATE ITHACA_DEFAULT_SAMPLE_RATE
#define DEFAULT_JUCE_BLOCK_SIZE ITHACA_DEFAULT_BLOCK_SIZE
#define VOICE_GAIN ITHACA_DEFAULT_VOICE_GAIN
#define DEFAULT_VELOCITY ITHACA_DEFAULT_VELOCITY
#define MAX_JUCE_BLOCK_SIZE ITHACA_MAX_BLOCK_SIZE
#define ENVELOPE_TRIGGERS_END_ATTACK ITHACA_ENVELOPE_TRIGGERS_END_ATTACK
#define ENVELOPE_TRIGGERS_END_RELEASE ITHACA_ENVELOPE_TRIGGERS_END_RELEASE

// ============================================================================
// END OF CONFIGURATION
// ============================================================================
